name: Java Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Personal Tests
        run: mvn -B clean test

      - name: Send Telegram message on success
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ "-4237518141" }}
          token: ${{ "7033090013:AAGOD_9JY7F7HXMhrenxdZT7PajVOj_zHRQ" }}
          message: |
            ${{ job.status }}: Tests ${{ job.status == 'success' && 'passed' || 'failed' }}.
